[tool.poetry]
name = "pyright-poetry"
version = "0.1.0"
description = ""
authors = ["Joachim Jablon <ewjoachim@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyright = "^1.1.357"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
